version: '2'
services:
        nginx:
                image: nginx
                container_name: nginx
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/home:/etc/nginx/home
                        - ./nginx/webui-aria2:/etc/nginx/webui-aria2  
                ports:
                        - "8080:8080"
                        - "8443:443"
                        - "9100:9100"
